# Generated by Django 5.2.11 on 2026-02-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(max_length=20, unique=True)),
                (
                    "password_hash",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("nickname", models.CharField(blank=True, max_length=64, null=True)),
                ("avatar_url", models.CharField(blank=True, max_length=512, null=True)),
                ("gender", models.SmallIntegerField(blank=True, null=True)),
                ("status", models.SmallIntegerField(default=1)),
                ("minor_mode", models.SmallIntegerField(default=0)),
                (
                    "minor_mode_pwd",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_bazi_edit_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
    ]
